新增 RSA PKCS1 加解密功能以兼容境外接口
wechatpay-apiv3/wechatpay-go pull request #109
Opened 2022-05-13 11:21 UTC by lddssxy

1. 增加 RSA PKCS1 加解密功能
2. 增加PKCS1相应测试，调整测试中直接用公共库进行解密验证加密，再用加密功能来验证解密。

2022-05-16 03:19 UTC, EmmetZC requested changes

2022-05-16 03:19 UTC, EmmetZC commented on utils/rsa_crypto.go
> +// EncryptPKCS1WithPublicKey 使用PKCS1 padding方式用公钥进行加密
之前因为只提供一种加解密规范的实现，所以注释写的比较简单。

这里麻烦把原本的 `XXXOAEPXXX`接口的注释也都加上「使用 OAEP 方式」这样的字眼吧。

2022-05-16 03:19 UTC, EmmetZC commented on utils/rsa_crypto.go
> +func DecryptPKCS1(ciphertext string, privateKey *rsa.PrivateKey) (message string, err error) {
既然 Golang `crypto` 库中把 PKCS#1 v1.5 命名为 `XXXPKCS1v15`，我们也采用同样的命名吧。

2022-05-16 10:09 UTC, lddssxy commented on utils/rsa_crypto_test.go
> +	ciphertext, err = EncryptPKCS1WithCertificate(message, certificate)
已修改哈

2022-05-16 10:09 UTC, lddssxy commented on utils/rsa_crypto.go
> +// EncryptPKCS1WithPublicKey 使用PKCS1 padding方式用公钥进行加密
注释已调整

2022-05-16 10:10 UTC, lddssxy commented on utils/rsa_crypto.go
> +func DecryptPKCS1(ciphertext string, privateKey *rsa.PrivateKey) (message string, err error) {
已修改哈

2022-05-16 12:13 UTC, EmmetZC commented on utils/rsa_crypto_test.go
> +	privateKey  *rsa.PrivateKey
整个 package 是共享命名空间的，所以测试中需要设置一些全局量的话，最好能加一些具体场景的前缀，可以避免一些不必要的冲突。

2022-05-16 12:16 UTC, EmmetZC commented on utils/rsa_crypto_test.go
> +	// 使用OAEP paading方式对证书加密
`paading` typo

2022-05-16 12:26 UTC, EmmetZC requested changes

2022-05-16 12:26 UTC, EmmetZC commented on utils/rsa_crypto_test.go
> +	decryptMessageBytes, _ := rsa.DecryptOAEP(sha1.New(), rand.Reader, privateKey, decodedCiphertext, nil)
这里没有接 `err`，下面的 `require.NoError(t, err)` 没意义

2022-05-17 08:57 UTC, lddssxy commented on utils/rsa_crypto_test.go
> +	privateKey  *rsa.PrivateKey
已修改

2022-05-17 08:57 UTC, lddssxy commented on utils/rsa_crypto_test.go
> +	// 使用OAEP paading方式对证书加密
已修改哈

2022-05-17 08:57 UTC, lddssxy commented on utils/rsa_crypto_test.go
> +	decryptMessageBytes, _ := rsa.DecryptOAEP(sha1.New(), rand.Reader, privateKey, decodedCiphertext, nil)
已调整

2022-05-17 10:55 UTC, alexkie007 approved these changes

2022-05-17 11:43 UTC, xy-peng commented
@lddssxy 请处理下 static check 发现的问题，可以在 review 页面看到

2022-05-18 02:07 UTC, xy-peng approved these changes

2022-05-18 02:09 UTC, EmmetZC approved these changes

2022-05-19 01:57 UTC, merged