服务商小程序支付增加PrepayWithRequestPayment接口
wechatpay-apiv3/wechatpay-go pull request #164
Opened 2023-02-07 14:13 UTC by zhenyonghou

由于我目前做的是小程序项目，目前仅为小程序增加了该接口，app，h5的还没支持。做了支付测试，没问题。

2023-02-08 02:54 UTC, xy-peng requested changes
给自定义类型加上 `String()` 方法吧，这样调试时打印字段值，而不是指针地址

2023-02-08 02:54 UTC, xy-peng commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
可能下单的参数中没有 SubAppid。建议改成有 SubAppid 用 SubAppid，没有的话用 Appid

2023-02-09 11:53 UTC, zhenyonghou commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
我的理解是：虽然接口文档中sub_appid是可选参数，但调用这个便捷接口就必须传SubAppid，SubAppid用来计算签名，否则签名无法计算，调用这个接口就失去意义了。调用方把子商户的Appid赋值给SubAppid。

2023-02-10 03:22 UTC, xy-peng commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
签名的计算跟appid无关，只跟商户号有关系。调起支付签名中的appid参数可以传appid，也可以传sub_appid。

2023-02-13 01:00 UTC, zhenyonghou commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
“建议改成有 SubAppid 用 SubAppid，没有的话用 Appid”这里的Appid指的是服务商的appid（sp_appid）吗？这里只有sp_appid和sub_appid。我对文档理解有点问题，一直认为appid是指的子商户的。

2023-02-13 08:19 UTC, xy-peng commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
想起我们之前 Java 的做法了，是提供一个输入参数，指定调起支付的 appid，可参考[相关代码](https://github.com/wechatpay-apiv3/wechatpay-java/blob/9a76cb05d68e951c45cd731f33663f30b1578617/service/src/main/java/com/wechat/pay/java/service/partnerpayments/jsapi/JsapiServiceExtension.java#L53)。

更准确地说，调起支付签名时 appid，对应调起支付时应用的 appid。这个应用既可能是服务商的应用，也可能是子商户的应用。“有 SubAppid 用 SubAppid，没有的话用 Appid”的策略并不正确。我们是允许下单时同时传 sub_appid/sp_appid，但是拉起支付的应用是服务商的。

还得请你再修改下。

2023-02-14 01:31 UTC, zhenyonghou commented on services/partnerpayments/jsapi/api_jsapi_request_payment.go
> +	resp.Appid = req.SubAppid
已修改

2023-02-14 06:33 UTC, xy-peng approved these changes

2023-02-14 06:58 UTC, EmmetZC approved these changes

2023-02-14 07:09 UTC, merged