fx: notify/handler  修正了支付回调通知
wechatpay-apiv3/wechatpay-go pull request #34
Opened 2021-07-10 17:17 UTC by cupen

修正了两个问题：
* 错误地使用了 request.GetBody 。 Body 和 GetBody 用哪个得看是 client 端还是 server 端。
  go 的这个实现比较坑，需要看注释才能明白。参考：
  ```go
    // Body is the request's body.
    //
    // For client requests, a nil body means the request has no
    // body, such as a GET request. The HTTP Client's Transport
    // is responsible for calling the Close method.
    //
    // For server requests, the Request Body is always non-nil
    // but will return EOF immediately when no body is present.
    // The Server will close the request body. The ServeHTTP
    // Handler does not need to.
    //
    // Body must allow Read to be called concurrently with Close.
    // In particular, calling Close should unblock a Read waiting
    // for input.
    Body io.ReadCloser

    // GetBody defines an optional func to return a new copy of
    // Body. It is used for client requests when a redirect requires
    // reading the body more than once. Use of GetBody still
    // requires setting Body.
    //
    // For server requests, it is unused.
    GetBody func() (io.ReadCloser, error) // Go 1.8
  ```
  https://golang.org/pkg/net/http/#Request

* 实际支付后收到的回调通知里并未发现 RequestID 请求头，但是文档 [APIv3](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml) 说有。我之前在文档那反馈了，暂无答复。为了先跑通代码，我就先斩后奏去掉了对 RequestID 的引用。

2021-07-10 17:29 UTC, cupen commented
关于 RequestID ，有必要请贵厂内部同步一下具体是怎样实现的。
我收到的支付通知的 http 请求是这样的（已脱敏处理）：
```
POST /略略略 HTTP/1.1
Host: 略略略
X-Real-Ip: 略略略
X-Forwarded-Proto: https
Connection: close
Wechatpay-Nonce: 略略略
Wechatpay-Serial: 略略略
X-Forwarded-For: 略略略
Pragma: no-cache
User-Agent: Mozilla/4.0
Content-Length: 1019
Content-Type: application/json
Wechatpay-Signature:  略略略
Wechatpay-Timestamp: 1625886357
Accept: */*

{
    "create_time": "2021-07-09T17:01:48+08:00",
    "event_type": "TRANSACTION.SUCCESS",
    "id": "略略略",
    "resource": {
        "algorithm": "AEAD_AES_256_GCM",
        "associated_data": "transaction",
        "ciphertext": "略略略",
        "nonce": "HwO1zBccs0bY",
        "original_type": "transaction"
    },
    "resource_type": "encrypt-resource",
    "summary": "支付成功"
}
```

2021-07-11 08:14 UTC, EmmetZC requested changes
> 两个问题：
> 
> * 错误地使用了 request.GetBody 。 Body 和 GetBody 用哪个得看是 client 端还是 server 端。
>   go 的这个实现比较坑，需要看注释才能明白。参考：  https://golang.org/pkg/net/http/#Request
>   ```go
>     // Body is the request's body.
>     //
>     // For client requests, a nil body means the request has no
>     // body, such as a GET request. The HTTP Client's Transport
>     // is responsible for calling the Close method.
>     //
>     // For server requests, the Request Body is always non-nil
>     // but will return EOF immediately when no body is present.
>     // The Server will close the request body. The ServeHTTP
>     // Handler does not need to.
>     //
>     // Body must allow Read to be called concurrently with Close.
>     // In particular, calling Close should unblock a Read waiting
>     // for input.
>     Body io.ReadCloser
>   
>     // GetBody defines an optional func to return a new copy of
>     // Body. It is used for client requests when a redirect requires
>     // reading the body more than once. Use of GetBody still
>     // requires setting Body.
>     //
>     // For server requests, it is unused.
>     GetBody func() (io.ReadCloser, error) // Go 1.8
>   ```
> * 实际支付后收到的回调通知里并未发现 RequestID 请求头，但是文档 [APIv3](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay4_1.shtml) 说有。我之前在文档那反馈了，暂无答复。为了先跑通代码，我就先斩后奏去掉了对 RequestID 的引用。


确实，这个是我们没有研究清楚 go 语言中 http.Request 的特性导致的错误，感谢纠正。
这一错误没有被检查出来也是因为我们在单元测试中错误地使用了 `http.NewRequest` 来创建测试用 `Request`，事实上为了测试`HTTPHandler`，应该是用 `httptest.NewRequest` 来创建输入Request。

还请对 `notify_test.go` 中的测试用例进行更新。

2021-07-11 08:14 UTC, EmmetZC commented on core/notify/notify.go
> -
为了防止body reader 被耗尽后无法再次读取，一般建议重设一下 request.Body
另外这里需要关闭 request.Body
```golang
body, err := ioutil.ReadAll(request.Body)
if err != nil {
	return nil, fmt.Errorf("read request body err: %v", err)
}

_ = request.Body.Close()
request.Body = ioutil.NopCloser(bytes.NewBuffer(body))
```

2021-07-11 08:14 UTC, EmmetZC commented on core/auth/validators/wechat_pay_validator.go
>  		return err
`newWechatPayHeaders` 方法输出的错误信息太简单，这里应该进行一下二次包装，以求提供更完整的错误信息。

2021-07-11 08:14 UTC, EmmetZC commented on core/auth/validators/wechat_pay_validator.go
> +	rs.SerialNo, err = getHeader(consts.WechatPaySerial)
考虑到应答中的 Request-ID 能帮助开发者更快联系微信支付进行问题研究，建议保留 Request-ID 的取出，只是移除对其必要性的检查，并且在后续的错误中包含 Request-ID 。

2021-07-11 12:53 UTC, cupen commented on core/auth/validators/wechat_pay_validator.go
> +	rs.SerialNo, err = getHeader(consts.WechatPaySerial)
@EmmetZC 我也在琢磨这事。实际的 RequestID 似乎转移到 body 中了，需要 json 解析一下才能拿到。我回头看看。

2021-07-11 13:16 UTC, cupen commented on core/notify/notify.go
> -
@EmmetZC  ok, `Close` 补上了。
我觉得按真实的 API 实现读一次就好，营造可反复读的假象有耍诡计之嫌。反复读不一定非要在这个标准库 API 上做，可以包个上下文保存 body 。

2021-07-11 13:22 UTC, cupen commented on core/auth/validators/wechat_pay_validator.go
> +	rs.SerialNo, err = getHeader(consts.WechatPaySerial)
@EmmetZC 想了想，结合前面的 body 问题，我干脆给 notify 加一个正儿八经的上下文对象吧，其用于表示 notify 本身，由它来处理 header 和 body ，然后提供一个 Verifiable 接口暴露给 validator 完事，validator 只管执行 verify。
我稍微重构下就好。

2021-07-12 03:29 UTC, cupen commented on core/auth/validators/wechat_pay_validator.go
> +	rs.SerialNo, err = getHeader(consts.WechatPaySerial)
@EmmetZC  RequestID 加到错误日志里了。

2021-07-12 03:30 UTC, cupen commented on core/auth/validators/wechat_pay_validator.go
>  		return err
@EmmetZC  加了 request-id
```go
args, err := newWechatpayHeaders(header)
if err != nil {
	return fmt.Errorf("%w request-id=[%s]", err, requestId)
}
```

2021-07-12 11:01 UTC, cupen commented on core/auth/validators/wechat_pay_validator.go
>  		return err
@EmmetZC  testcase 已更新。 但有两个其他功能的测试例子报错，我摆不平……  有空可以在 main 分支上解决一下，我随时可以 rebase .

2021-07-12 11:29 UTC, cupen commented
@EmmetZC  有两个 case 似乎原本就是错的，看是怎样处理？

```
❯ go test ./...
# github.com/wechatpay-apiv3/wechatpay-go/services/certificates [github.com/wechatpay-apiv3/wechatpay-go/services/certificates.test]
services/certificates/api_certificates_test.go:18:42: undefined: consts.MchPrivateKey
services/certificates/api_certificates_test.go:21:33: undefined: consts.MchID
services/certificates/api_certificates_test.go:21:47: undefined: consts.SerialNo
services/certificates/api_certificates_test.go:40:42: undefined: consts.MchPrivateKey
services/certificates/api_certificates_test.go:42:46: undefined: consts.WechatPayCertificate
services/certificates/api_certificates_test.go:45:33: undefined: consts.MchID
services/certificates/api_certificates_test.go:45:47: undefined: consts.SerialNo
?   	github.com/wechatpay-apiv3/wechatpay-go/cmd/wechatpay_download_certs	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core	(cached)
?   	github.com/wechatpay-apiv3/wechatpay-go/core/auth	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/credentials	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/signers	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/validators	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/verifiers	(cached)
?   	github.com/wechatpay-apiv3/wechatpay-go/core/cipher	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/ciphers	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/decryptors	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/encryptors	(cached)
?   	github.com/wechatpay-apiv3/wechatpay-go/core/consts	[no test files]
--- FAIL: TestAutoCertificateDownloader (0.11s)
    downloader_mgr_test.go:37: 
        	Error Trace:	downloader_mgr_test.go:37
        	Error:      	Received unexpected error:
        	            	error http response:[StatusCode: 401 Code: "SIGN_ERROR"
        	            	Message: 商户号不存在
        	            	Header:
        	            	 - Server=[nginx]
        	            	 - Content-Type=[application/json; charset=utf-8]
        	            	 - Connection=[keep-alive]
        	            	 - Cache-Control=[no-cache, must-revalidate]
        	            	 - X-Content-Type-Options=[nosniff]
        	            	 - Date=[Mon, 12 Jul 2021 11:26:13 GMT]
        	            	 - Content-Length=[52]
        	            	 - Keep-Alive=[timeout=8]
        	            	 - Request-Id=[08D5CDB087061084041885CBEEA30620BB0F2894AD05-269546538]
        	            	 - Content-Language=[zh-CN]]
        	Test:       	TestAutoCertificateDownloader
--- FAIL: TestNewCertificateDownloaderWithClient (0.09s)
    downloader_test.go:32: 
        	Error Trace:	downloader_test.go:32
        	Error:      	Received unexpected error:
        	            	error http response:[StatusCode: 401 Code: "SIGN_ERROR"
        	            	Message: 商户号不存在
        	            	Header:
        	            	 - Server=[nginx]
        	            	 - Content-Type=[application/json; charset=utf-8]
        	            	 - Cache-Control=[no-cache, must-revalidate]
        	            	 - X-Content-Type-Options=[nosniff]
        	            	 - Date=[Mon, 12 Jul 2021 11:26:13 GMT]
        	            	 - Content-Length=[52]
        	            	 - Connection=[keep-alive]
        	            	 - Keep-Alive=[timeout=8]
        	            	 - Request-Id=[08D5CDB0870610BE0418A7B8B74C20BD2E28F0B202-269546538]
        	            	 - Content-Language=[zh-CN]]
        	Test:       	TestNewCertificateDownloaderWithClient
--- FAIL: TestNewCertificateDownloader (0.09s)
    downloader_test.go:60: 
        	Error Trace:	downloader_test.go:60
        	Error:      	Received unexpected error:
        	            	error http response:[StatusCode: 401 Code: "SIGN_ERROR"
        	            	Message: 商户号不存在
        	            	Header:
        	            	 - Content-Length=[52]
        	            	 - Connection=[keep-alive]
        	            	 - X-Content-Type-Options=[nosniff]
        	            	 - Server=[nginx]
        	            	 - Content-Type=[application/json; charset=utf-8]
        	            	 - Cache-Control=[no-cache, must-revalidate]
        	            	 - Request-Id=[08D5CDB0870610AA051885CBEEA30620CD092891C702-269546538]
        	            	 - Content-Language=[zh-CN]
        	            	 - Date=[Mon, 12 Jul 2021 11:26:13 GMT]
        	            	 - Keep-Alive=[timeout=8]]
        	Test:       	TestNewCertificateDownloader
FAIL
FAIL	github.com/wechatpay-apiv3/wechatpay-go/core/downloader	0.294s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/notify	(cached)
?   	github.com/wechatpay-apiv3/wechatpay-go/core/option	[no test files]
?   	github.com/wechatpay-apiv3/wechatpay-go/services	[no test files]
FAIL	github.com/wechatpay-apiv3/wechatpay-go/services/certificates [build failed]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/fileuploader	(cached) [no tests to run]
?   	github.com/wechatpay-apiv3/wechatpay-go/services/payments	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/app	(cached) [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/h5	(cached) [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/jsapi	(cached) [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/native	(cached) [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/refunddomestic	(cached) [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/utils	(cached)
ok  	github.com/wechatpay-apiv3/wechatpay-go/utils/task	(cached)
FAIL
```

2021-07-12 11:31 UTC, xy-peng commented
> @EmmetZC 有两个 case 似乎原本就是错的，看是怎样处理？

gomonkey的原因，需要用`go test -gcflags=all=-l`

2021-07-12 11:31 UTC, cupen commented
我躺平了…… 那俩 case 期望能在 main 分支上修复一下，然后这里 rebase 一下就最好了。:smile:

2021-07-12 11:35 UTC, cupen commented
> > @EmmetZC 有两个 case 似乎原本就是错的，看是怎样处理？
> 
> gomonkey的原因，需要用`go test -gcflags=all=-l`

OK，有效.
```
❯ go test ./... -gcflags=all=-l
?   	github.com/wechatpay-apiv3/wechatpay-go/cmd/wechatpay_download_certs	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core	0.051s
?   	github.com/wechatpay-apiv3/wechatpay-go/core/auth	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/credentials	0.005s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/signers	0.014s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/validators	0.002s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/auth/verifiers	0.004s
?   	github.com/wechatpay-apiv3/wechatpay-go/core/cipher	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/ciphers	0.024s
# github.com/wechatpay-apiv3/wechatpay-go/services/certificates [github.com/wechatpay-apiv3/wechatpay-go/services/certificates.test]
services/certificates/api_certificates_test.go:18:42: undefined: consts.MchPrivateKey
services/certificates/api_certificates_test.go:21:33: undefined: consts.MchID
services/certificates/api_certificates_test.go:21:47: undefined: consts.SerialNo
services/certificates/api_certificates_test.go:40:42: undefined: consts.MchPrivateKey
services/certificates/api_certificates_test.go:42:46: undefined: consts.WechatPayCertificate
services/certificates/api_certificates_test.go:45:33: undefined: consts.MchID
services/certificates/api_certificates_test.go:45:47: undefined: consts.SerialNo
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/decryptors	0.011s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/cipher/encryptors	0.017s
?   	github.com/wechatpay-apiv3/wechatpay-go/core/consts	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/downloader	11.037s
ok  	github.com/wechatpay-apiv3/wechatpay-go/core/notify	0.006s
?   	github.com/wechatpay-apiv3/wechatpay-go/core/option	[no test files]
?   	github.com/wechatpay-apiv3/wechatpay-go/services	[no test files]
FAIL	github.com/wechatpay-apiv3/wechatpay-go/services/certificates [build failed]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/fileuploader	0.014s [no tests to run]
?   	github.com/wechatpay-apiv3/wechatpay-go/services/payments	[no test files]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/app	0.011s [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/h5	0.005s [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/jsapi	0.004s [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/payments/native	0.002s [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/services/refunddomestic	0.002s [no tests to run]
ok  	github.com/wechatpay-apiv3/wechatpay-go/utils	0.007s
ok  	github.com/wechatpay-apiv3/wechatpay-go/utils/task	14.009s
```

2021-07-13 02:55 UTC, HelloTQ commented
刚接完，也遇到了相同的问题，啥时候在main分支上修复呀

2021-07-13 03:09 UTC, EmmetZC commented
考虑到本PR提交了不止一个内容的修改，其中一些修改尚未统一意见，暂时不适于合并至`main`分支中。
为了尽快修复 `notify.Handler` 的读取问题，保证开发者的正常使用，另开了PR #38。
特此注明。

2021-07-13 04:09 UTC, cupen commented
收到。

2021-07-13 04:09 UTC, closed without merging