优化了README
wechatpay-apiv3/wechatpay-go pull request #66
Opened 2021-08-30 09:53 UTC by xy-peng

1. 尽快的进入示例，尽快的让开发者动起手来
2. 示例真实可用
3. 内容补充一些“为什么”
4. 用了一些引用来串内容，把升级内容挪到upgrading.md中去了

2021-08-31 08:54 UTC, EmmetZC commented on README.md
> +当前版本为测试版本，微信支付会尽量保持向后兼容。但可能因为可用性或易用性，同历史版本存在不兼容。如果你之前使用版本 `<= v0.2.2`，请参考[升级指南](UPGRADING.md)升级你的系统。
应该是升级依赖，不是升级系统吧。

2021-08-31 15:57 UTC, Eric-Lee-Handyman commented on README.md
> +也就是说，应答中的证书序列号，是**微信支付平台证书**的序列号，相比发起请求的**商户API证书序列号**是不一致的。
“相比发起请求的**商户API证书序列号**是不一致的。”
读起来有点不通顺，建议改成：这跟请求使用的**商户API证书序列号**是不一样的。

2021-09-01 02:07 UTC, xy-peng commented on README.md
> +当前版本为测试版本，微信支付会尽量保持向后兼容。但可能因为可用性或易用性，同历史版本存在不兼容。如果你之前使用版本 `<= v0.2.2`，请参考[升级指南](UPGRADING.md)升级你的系统。
改成“升级前请参考升级指南”。

2021-09-01 02:11 UTC, xy-peng commented on README.md
> +`resp` 是 Unmarshal 后的应答（当前示例为 `*service.certificates.Certificate`）。
本来想写反序列化的，也担心开发者的理解成本，使用`UnmarshalJSON`是不是更好？

2021-09-01 02:31 UTC, EmmetZC commented on README.md
> +	mchPrivateKey, err := utils.LoadPrivateKeyWithPath("/path/to/merchant/apiclient_key.pem")
这个是因为本地加载私钥有两种方式：1.从本地文件中读取；2. 从集中私钥存储中读取。
如果两种都支持的话，初始化的方法就要多写一个。加载证书也是一样的，如果都这样处理就感觉比较麻烦了，所以就选了让开发者加载好以后再传进来。

2021-09-01 07:29 UTC, xy-peng commented on README.md
> +	mchPrivateKey, err := utils.LoadPrivateKeyWithPath("/path/to/merchant/apiclient_key.pem")
豪哥的意思是，为什么不把私钥路径作为常量放到var()里面去吧

2021-09-01 07:38 UTC, xy-peng commented on README.md
> +	mchPrivateKey, err := utils.LoadPrivateKeyWithPath("/path/to/merchant/apiclient_key.pem")
从商户侧的实践来看，大部分都是通过配置来传递这几个参数的，可能不会独立出来定义。

定义变量方便命名清楚表达含义和写注释。而私钥路径就没有这个目的，所以直接用常量了。

2021-09-02 03:20 UTC, EmmetZC requested changes

2021-09-02 03:20 UTC, EmmetZC commented on README.md
> ++ 方法二：如果没有使用 `WithWechatPayAutoAuthCipher`，则需要先手动注册下载器了。
把这个「了」去了吧

2021-09-02 03:20 UTC, EmmetZC commented on README.md
> +如果是尚未支持的回调消息体，将内容解析至 `map[string]interface{}`。
改成这样是不是好点：

如果SDK尚未提供回调消息的结构体，将内容解析至 `map[string]interface{}`

2021-09-02 03:20 UTC, EmmetZC commented on README.md
> +SDK 在单元测试中使用了`gomonkey`和`require`，测试前请确认相关的依赖。使用以下命令获取所有的依赖。
SDK 在单元测试用使用了 [agiledragon/gomonkey](github.com/agiledragon/gomonkey) 与 [stretchr/testify](https://github.com/stretchr/testify)，

2021-09-02 03:23 UTC, xy-peng commented on README.md
>  [微信支付 API v3](https://wechatpay-api.gitbook.io/wechatpay-api-v3/) 官方Go语言客户端代码库。
商户平台还不支持 URL 锚点，没法到具体的小节

2021-09-03 02:27 UTC, EmmetZC approved these changes

2021-09-03 02:35 UTC, Eric-Lee-Handyman approved these changes

2021-09-03 02:40 UTC, merged