Update README.md
wechatpay-apiv3/wechatpay-go pull request #83
Opened 2021-11-03 09:37 UTC by xiaokang-chen

在我接入微信支付SDK的时候，发现回调通知解密推荐案例中，其中的client在后续的获取平台证书访问器中并没有用到。后面获取平台证书访问器只需要”证书相关功能“。所以为了更好的让新手接入微信SDK，这里只需要调用WithWechatPayAutoAuthCipher方法去初始化即可。在我实际的业务中也发现仅调用WithWechatPayAutoAuthCipher初始化方法是可行的

2021-11-03 10:46 UTC, xy-peng requested changes

2021-11-03 10:46 UTC, xy-peng commented on README.md
> +// 由于在回调通知的解密过程中无需使用client发送请求，所以这里不用获取client
> 由于在回调通知的解密过程中无需使用client发送请求

这句话表述不完全准确，对回调的处理包括，验签和解密

> 使用商户私钥等初始化 client，并使它具有自动定时获取微信支付平台证书的能力

这句话也可以改写一下。你试着用简洁准确的语言重新描述一下？

2021-11-03 10:46 UTC, xy-peng commented on README.md
> +// 由于在回调通知的解密过程中无需使用client发送请求，所以这里不用获取client
另外，如果没有client，直接用方法二会更好。所以删掉是不是并不是很清晰，而需要把选择条件说得更清楚？

```
ctx := context.Background()
// 这是一个单纯的回调处理进程，没有使用 WithWechatPayAutoAuthCipher 创建商户的 client，则需要手动注册下载器
err := downloader.MgrInstance().RegisterDownloaderWithPrivateKey(ctx, mchPrivateKey, mchCertificateSerialNumber, mchID, mchAPIV3Key)

// 注册完成，获取平台证书访问器
certVisitor := downloader.MgrInstance().GetCertificateVisitor(mchID)
handler := notify.NewNotifyHandler(mchAPIv3Key, verifiers.NewSHA256WithRSAVerifier(certVisitor))
```

2021-11-05 02:39 UTC, EmmetZC commented
![image](https://user-images.githubusercontent.com/6105862/140448143-3f7c5b8c-2868-4eb5-9e5e-2ddc92ed21d2.png)

如图所示，我们其实给出了三种初始化`notify.Handler` 的方法，第一种使用方法的前提是「如果你像 发送请求 那样使用 WithWechatPayAutoAuthCipher 初始化 `core.Client`」，所以才有出现了先初始化Client，然后顺便就能初始化 `notify.Handler`。

你说的这种情况，其实直接适用于我们提供的第二种方案：「如果没有使用 WithWechatPayAutoAuthCipher，则需要先手动注册下载器」。

这里表述上可能不太好让人一眼看出来如何选择，我们可以讨论下这里怎么改进下描述、格式。

你提到的这个修改，可能更难以让人理解，因为在本SDK的设计中，`option.WithXXX` 是专门为了初始化Client设计的，用来初始化`notify.Handler`并不合适。

2021-11-08 02:23 UTC, xiaokang-chen commented
> ![image](https://user-images.githubusercontent.com/6105862/140448143-3f7c5b8c-2868-4eb5-9e5e-2ddc92ed21d2.png)
> 
> 如图所示，我们其实给出了三种初始化`notify.Handler` 的方法，第一种使用方法的前提是「如果你像 发送请求 那样使用 WithWechatPayAutoAuthCipher 初始化 `core.Client`」，所以才有出现了先初始化Client，然后顺便就能初始化 `notify.Handler`。
> 
> 你说的这种情况，其实直接适用于我们提供的第二种方案：「如果没有使用 WithWechatPayAutoAuthCipher，则需要先手动注册下载器」。
> 
> 这里表述上可能不太好让人一眼看出来如何选择，我们可以讨论下这里怎么改进下描述、格式。
> 
> 你提到的这个修改，可能更难以让人理解，因为在本SDK的设计中，`option.WithXXX` 是专门为了初始化Client设计的，用来初始化`notify.Handler`并不合适。

但是描述可能需要修改一下，因为对于新手没有看过源码的人来说，一般会直接把方法1直接copy到代码里，结果发现在编译器层面，client报错（这个client没有用到），就会怀疑是不是代码错了

2021-11-26 03:35 UTC, closed without merging