fix: code struct make it like golang
wechatpay-apiv3/wechatpay-go pull request #96
Opened 2022-01-12 06:43 UTC by Jonescy

对整体逻辑影响不大，符合go的代码风格。

2022-01-12 07:19 UTC, EmmetZC requested changes

2022-01-12 07:19 UTC, EmmetZC commented on core/client.go
> +		if regXMLTypeCheck.MatchString(contentType) {
这里少了个 `else` 来的。

2022-01-12 12:26 UTC, Jonescy commented on core/client.go
> +		if regXMLTypeCheck.MatchString(contentType) {
sorry，应该加上，不然逻辑变了

2022-01-12 16:07 UTC, EmmetZC approved these changes
LGTM

2022-01-13 02:51 UTC, alexkie007 approved these changes

2022-01-13 02:53 UTC, merged